import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const products = [
  { id: 'voicepad', number: '01', name: 'VoicePad', category: 'AI productivity', status: 'BETA', tone: 'gold', summary: 'Speak naturally. Get a clear, useful note.', copy: 'A voice-first workspace for recording ideas, transcribing conversations, finding the thread and turning it into action.', features: ['Voice capture', 'AI transcription', 'Local-first notes', 'AI summaries'], repo: 'https://github.com/Holaoluwakintan/Voicepad-web' },
  { id: 'bible-arena', number: '02', name: 'Bible Arena', category: 'Knowledge game', status: 'PROTOTYPE', tone: 'blue', summary: 'Learn Scripture. Test yourself. Challenge others.', copy: 'A modern competitive game built around Bible Quiz, Daily Challenge, AI Battle, progression and friendly competition.', features: ['Bible Quiz', 'Daily Challenge', 'XP and streaks', 'Leaderboards'], repo: 'https://github.com/Holaoluwakintan/Bible-Arena' },
  { id: 'blossom-books', number: '03', name: 'Blossom Books', category: 'Reading platform', status: 'BUILDING', tone: 'rose', summary: 'A home for the whole story.', copy: 'A reading and publishing platform with discovery, a calm reader, author pages, writer tools, reviews and creator workflows.', features: ['Discover', 'In-browser reader', 'Writer Studio', 'Author pages'], repo: 'https://github.com/Holaoluwakintan/Blossom-Books' },
];

function Mark() { return <span className="mark" aria-hidden="true"><i /><i /><i /><i /></span>; }
function Arrow() { return <span aria-hidden="true">↗</span>; }

function Layout({ children, route, setRoute }) {
  const [menu, setMenu] = useState(false);
  useEffect(() => { document.title = route === '/' ? 'BLOSSOMING — Stories, products and ideas' : `${route.slice(1).replaceAll('-', ' ')} — BLOSSOMING`; }, [route]);
  const go = (path) => { window.history.pushState({}, '', path); setRoute(path); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  useEffect(() => { const fn = () => setRoute(window.location.pathname); window.addEventListener('popstate', fn); return () => window.removeEventListener('popstate', fn); }, [setRoute]);
  return <div className="app"><header className="nav"><button className="brand" onClick={() => go('/')}><Mark /><span>BLOSSOMING<small>OLAOLUWA MICHAEL</small></span></button><nav className={menu ? 'navlinks open' : 'navlinks'}><button onClick={() => go('/')}>Home</button><button onClick={() => go('/products')}>Products</button><button onClick={() => go('/about')}>About</button><a href="https://github.com/Holaoluwakintan" target="_blank" rel="noreferrer">GitHub <Arrow /></a></nav><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? 'Close' : 'Menu'}</button></header>{children}<footer><div><button className="brand" onClick={() => go('/')}><Mark /><span>BLOSSOMING<small>ONE POINT OF VIEW</small></span></button><p>A personal studio for stories, products and ideas made carefully.</p></div><div className="footerlinks"><span>Explore</span><button onClick={() => go('/products')}>Products</button><button onClick={() => go('/about')}>About</button><a href="mailto:michaelolaoluwag@gmail.com">Contact</a></div><div className="copyright">© {new Date().getFullYear()} Olaoluwa Michael</div></footer></div>;
}

function Home({ go }) { return <><main><section className="hero"><div className="eyebrow">PERSONAL STUDIO / 001</div><h1>Make things<br /><em>worth keeping.</em></h1><p className="lead">BLOSSOMING is the personal studio of Olaoluwa Michael — a place for stories, technology products, visual ideas and work that starts small and grows with intention.</p><div className="actions"><button className="button primary" onClick={() => go('/products')}>Explore the work <Arrow /></button><button className="textbutton" onClick={() => go('/about')}>About the studio <Arrow /></button></div><div className="hero-note"><span>Currently making</span><strong>Products, books &amp; useful ideas</strong><span className="pulse">● In progress</span></div></section><section className="statement"><div className="sectionlabel">THE STUDIO</div><div><h2>One point of view.<br /><em>Many ways to make.</em></h2><p>Some ideas become apps. Some become books. Some stay as questions for a while. BLOSSOMING is where they can share a home without becoming the same thing.</p></div></section><section className="preview"><div className="sectionhead"><div><div className="sectionlabel">SELECTED WORK</div><h2>Things taking shape.</h2></div><button className="textbutton" onClick={() => go('/products')}>View all products <Arrow /></button></div><div className="productgrid">{products.map(p => <ProductCard key={p.id} product={p} onClick={() => go('/products/' + p.id)} />)}</div></section><section className="closing"><div className="eyebrow">A NOTE FROM THE STUDIO</div><h2>Make it honest.<br /><em>Make it matter.</em></h2><button className="button light" onClick={() => go('/about')}>Meet the studio <Arrow /></button></section></main></>; }

function ProductCard({ product, onClick }) { return <article className={`productcard ${product.tone}`}><button onClick={onClick} className="productvisual"><span>{product.number}</span><b>{product.name.slice(0, 1)}</b><i>{product.category}</i></button><div className="productcopy"><div className="productmeta"><span>{product.category}</span><small>{product.status}</small></div><h3>{product.name}</h3><p>{product.summary}</p><button className="cardlink" onClick={onClick}>Explore product <Arrow /></button></div></article>; }

function Products({ go }) { return <main><section className="pagehero"><div className="eyebrow">BLOSSOMING / PRODUCTS</div><h1>Ideas made<br /><em>useful.</em></h1><p className="lead">A growing shelf of products and experiments built from a personal point of view — across technology, faith, creativity and learning.</p></section><section className="catalog"><div className="catalogintro"><div className="sectionlabel">THE PRODUCT SHELF</div><p>Clear status. Real work. No invented launch promises.</p></div><div className="productlist">{products.map(p => <ProductCard key={p.id} product={p} onClick={() => go('/products/' + p.id)} />)}</div><div className="future"><div><div className="sectionlabel">FUTURE DIRECTION</div><h2>Accountability Partner</h2><p>A concept for staying consistent, focused and supported. Still an idea — not presented as a shipped product.</p></div><span className="status">IDEA</span></div></section></main>; }

function ProductDetail({ product, go }) { return <main><section className={`detailhero ${product.tone}`}><button className="back" onClick={() => go('/products')}>← All products</button><div className="eyebrow">{product.category} / {product.status}</div><h1>{product.name}<em>.</em></h1><p className="detailtag">{product.summary}</p><a className="button primary" href={product.repo} target="_blank" rel="noreferrer">View repository <Arrow /></a></section><section className="detailbody"><div className="detailintro"><div className="sectionlabel">THE PRODUCT IDEA</div><h2>{product.copy}</h2></div><div className="featuregrid">{product.features.map((f, i) => <div className="feature" key={f}><span>0{i + 1}</span><h3>{f}</h3><p>Designed as part of a focused, useful product experience.</p></div>)}</div><div className="detailend"><span className="sectionlabel">CURRENT STAGE</span><h2>Built with intention.<br /><em>Still being shaped.</em></h2><button className="textbutton" onClick={() => go('/products')}>Back to products <Arrow /></button></div></section></main>; }

function About({ go }) { return <main><section className="pagehero abouthero"><div className="eyebrow">BLOSSOMING / ABOUT</div><h1>A studio for<br /><em>the things I make.</em></h1><p className="lead">I’m Olaoluwa Michael. BLOSSOMING is the space where I build products, write stories and follow ideas until they become something useful.</p></section><section className="aboutbody"><div className="sectionlabel">THE APPROACH</div><div className="aboutcopy"><h2>Start with curiosity.<br /><em>Stay with the work.</em></h2><p>I care about the space between technology and meaning — products that make a task lighter, stories that make a person think, and experiments that make the next question clearer.</p><p>This is a personal studio, not a corporation or a promise to have everything figured out. Some work is live, some is building, and some is still becoming.</p><button className="button primary" onClick={() => go('/products')}>See what’s being made <Arrow /></button></div></section></main>; }

function App() { const [route, setRoute] = useState(window.location.pathname); const go = (path) => { window.history.pushState({}, '', path); setRoute(path); window.scrollTo(0, 0); }; let page = <Home go={go} />; if (route === '/products') page = <Products go={go} />; else if (route === '/about') page = <About go={go} />; else if (route.startsWith('/products/')) { const product = products.find(p => route.endsWith(p.id)); page = product ? <ProductDetail product={product} go={go} /> : <Products go={go} />; } return <Layout route={route} setRoute={setRoute}>{page}</Layout>; }

createRoot(document.getElementById('root')).render(<App />);
